import { FaIconLibrary } from '@fortawesome/angular-fontawesome';
import {
  faHome,
  faSearch,
  faBell,
  faPlus,
  faUser,
  faCog,
  faSignOutAlt,
  faBars,
  faEye,
  faEyeSlash,
  faCheck,
  faTimes,
  faSpinner,
  faFileImage,
  faInfoCircle,
  faInfo,
  faHashtag,
  faMapMarkerAlt,
  faCalendarAlt,
  faBriefcase,
  faEnvelope,
  faLink,
  faIdCard,
  faQuoteLeft,
  faChevronDown,
  faChevronUp,
  faHeart,
  faComment,
  faBookmark,
  faFilter,
  faStar,
  faCompass,
  faUserFriends,
  faNewspaper,
  faImage,
  faDotCircle,
  faUpload,
  faTrash,
  faPaperPlane,
  faExclamationCircle,
  faPen,
  faHeading,
  faGlobe,
  faArrowUpRightFromSquare,
  faCamera,
  faCircleUser,
  faLocationDot,
} from '@fortawesome/free-solid-svg-icons';
import {
  faCommentDots,
  faBell as faBellRegular,
  faHeart as faHeartRegular,
  faBookmark as faBookmarkRegular,
  faComment as faCommentRegular,
  faUser as faUserRegular,
  faPlusSquare as faPlusSquareRegular,
  faArrowAltCircleRight as faArrowAltCircleRightRegular,
} from '@fortawesome/free-regular-svg-icons';
import {
  faTwitter,
  faGithub,
  faFacebook,
  faInstagram,
  faLinkedin,
} from '@fortawesome/free-brands-svg-icons';

export function initializeIcons(library: FaIconLibrary) {
  // Add icons to the library for convenient access in components
  library.addIcons(
    faHome,
    faSearch,
    faBell,
    faBellRegular,
    faPlus,
    faUser,
    faCog,
    faSignOutAlt,
    faBars,
    faCommentDots,
    faTwitter,
    faGithub,
    faEye,
    faEyeSlash,
    faCheck,
    faTimes,
    faSpinner,
    faFileImage,
    faInfoCircle,
    faInfo,
    faHashtag,
    faMapMarkerAlt,
    faCalendarAlt,
    faBriefcase,
    faEnvelope,
    faLink,
    faIdCard,
    faQuoteLeft,
    faFacebook,
    faInstagram,
    faLinkedin,
    faChevronDown,
    faChevronUp,
    faHeart,
    faHeartRegular,
    faComment,
    faBookmark,
    faBookmarkRegular,
    faFilter,
    faStar,
    faCompass,
    faUserFriends,
    faNewspaper,
    faImage,
    faDotCircle,
    faUpload,
    faTrash,
    faPaperPlane,
    faExclamationCircle,
    faPen,
    faHeading,
    faGlobe,
    faArrowUpRightFromSquare,
    faCamera,
    faCommentRegular,
    faUserRegular,
    faPlusSquareRegular,
    faArrowAltCircleRightRegular,
    faCircleUser,
    faLocationDot
  );
}
